--- 
title: "Wingspan Utilities"
author: "Noah Bolohan"
format:
  dashboard:
    nav-buttons:
      - icon: github
        href: https://github.com/NoahBolohan/wingspan-utilities
---

# Score analysis

```{r}
#| output: false
library(gsheet)
library(DT)
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(plotly)
library(dygraphs)

# load functions
lapply(
  list.files("./R", full.names = TRUE),
  source
)

df <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1K600qeRyYevSrMBUyevP4sZ4vRIBzq4ggCl3cLjHAvc#gid=2096833443')

df <- df |> mutate(game = 1:nrow(df), .before = 1)
stacked_player_scores <- lapply(1:7, iterative_pivot, df = df) |> bind_rows()

noah_scores <- filter(
  stacked_player_scores,
  Name == "Noah",
  score_type != "total_score"
)

noah_scores_total <- stacked_player_scores %>% filter(
  Name == "Noah",
  score_type == "total_score"
) %>% arrange(game)
```

## Row

### Column {width=30%}

#### {.toolbar}

Noah

Alex

Mila

#### Row

:::{.card title="General stats"}
* Games played: `r eval(nrow(noah_scores_total["score"]))`
* Max. score: `r eval(max(noah_scores_total["score"]))`
* Min. score: `r eval(min(noah_scores_total["score"]))`
:::

### Column {.tabset}
```{r}
#| title: Total score
#| out-width: 100%
dygraph(noah_scores_total[c("game","score")], main = "Total score")%>% 
  dyRangeSelector(dateWindow = c(nrow(noah_scores_total)-50,nrow(noah_scores_total)))
```

```{r}
#| title: Score breakdown
#| out-width: 100%
p <- ggplot(
  noah_scores,
  aes(
    x = pull(noah_scores["game"]),
    y = pull(noah_scores["score"]),
    fill = pull(noah_scores["score_type"])
  )
) + 
geom_area() +
xlab("Game number") +
ylab("Score") +
labs(fill="Score types")

ggplotly(p)
```

## Row

```{r}
#| title: Noah's games
datatable(
    filter(
    df,
    player_1_name == "Noah" | 
    player_2_name == "Noah" |
    player_3_name == "Noah" |
    player_4_name == "Noah" |
    player_5_name == "Noah" |
    player_6_name == "Noah" |
    player_7_name == "Noah"
    )
)
```

# Recorded games

## Row {height=70%}

```{r}
#| title: Human games
library(gsheet)
library(DT)
datatable(gsheet2tbl('https://docs.google.com/spreadsheets/d/1K600qeRyYevSrMBUyevP4sZ4vRIBzq4ggCl3cLjHAvc#gid=2096833443'))
```

## Row {height=70%}

```{r}
#| title: Automa games
library(gsheet)
library(DT)
datatable(gsheet2tbl('https://docs.google.com/spreadsheets/d/1K600qeRyYevSrMBUyevP4sZ4vRIBzq4ggCl3cLjHAvc#gid=0'))
```