$(document).ready(

    function () {

        // Initialize data attributes
        $("#automa_tracker_body").data(
            "automa_drawn_cards_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_eggs_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_hoard_token_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_forest_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_forest_end_of_round_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_forest_score",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_grassland_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_grassland_end_of_round_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_grassland_score",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_wetland_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_wetland_end_of_round_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_nectar_wetland_score",
            0
        );
        $("#automa_tracker_body").data(
            "automa_played_birds_counter",
            0
        );
        $("#automa_tracker_body").data(
            "automa_total_score_counter",
            0
        );
        $("#automa_tracker_body").data(
            "user_end_of_round_1_points",
            0
        );
        $("#automa_tracker_body").data(
            "user_end_of_round_2_points",
            0
        );
        $("#automa_tracker_body").data(
            "user_end_of_round_3_points",
            0
        );
        $("#automa_tracker_body").data(
            "user_end_of_round_4_points",
            0
        );
        $("#automa_tracker_body").data(
            "automa_end_of_round_1_points",
            0
        );
        $("#automa_tracker_body").data(
            "automa_end_of_round_2_points",
            0
        );
        $("#automa_tracker_body").data(
            "automa_end_of_round_3_points",
            0
        );
        $("#automa_tracker_body").data(
            "automa_end_of_round_4_points",
            0
        );
        $("#automa_tracker_body").data(
            "round_1_cube_counter",
            0
        );
        $("#automa_tracker_body").data(
            "round_2_cube_counter",
            0
        );
        $("#automa_tracker_body").data(
            "round_3_cube_counter",
            0
        );
        $("#automa_tracker_body").data(
            "round_4_cube_counter",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_round_1_end_goal",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_round_2_end_goal",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_round_3_end_goal",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_round_4_end_goal",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_difficulty",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_hoard_tokens",
            1
        );
        $("#automa_tracker_body").data(
            "enable_start_game_points_per_drawn_card",
            0
        );
        $("#automa_tracker_body").data(
            "enable_start_game_nectar",
            0
        );
    }
)