<?php
    echo "<div class='modal fade' data-bs-backdrop='static' data-keyboard='false' id='modal_no_web_app_url'>";
    echo "";
    echo "    <div class='modal-dialog' role='document'>";
    echo "";
    echo "        <div class='modal-content'>";
    echo "";
    echo "            <div class='modal-header p-0 justify-content-center' style='position:relative;'>";
    echo "";
    echo "                <h2 class='modal-title h2'>No Web App URL!</h2>";
    echo "                <button class='btn astext btn-close-settings' id='button_close_modal_no_web_app_url' style='position:absolute;right:1em;' type='button'>";
    echo "                    &#x274c;";
    echo "                </button>";
    echo "            </div>";
    echo "";
    echo "            <div class='modal-body' id='modal_no_web_app_url_body'>";
    echo "";
    echo "                <div class='row p-0 justify-content-center margin_auto' style='margin-top:1vh;' id='row_set_web_app_url'>";
    echo "";
    echo "                    <div class='col-12 p-0 align-self-center'>";
    echo "                        Cannot submit score to a Google Web App! Either:";
    echo "                        <ul>";
    echo "                            <li>No Web App URL has been shared with this application yet; or</li>";
    echo "                            <li>An invalid Web App URL has been shared with this application</li>";
    echo "                        </ul>";
    echo "                        If you've already generated a Web App URL, please paste it below:";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row p-0 justify-content-center margin_auto' style='margin-top:1vh;'></div>";
    echo "";
    echo "                    <div class='col-12 p-0'>";
    echo "                        <input class='w-100' id='input_web_app_url_from_submit_attempt' placeholder='Paste Web App URL here'>";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row p-0 justify-content-center margin_auto' style='margin-top:1vh;'>";
    echo "";
    echo "                    <div class='col-12 p-0' style='text-align: center;'>";
    echo "                        Otherwise, <a class='w-100' target='_blank' rel='noopener noreferrer' href='https://github.com/NoahBolohan/wingspan-utilities/blob/main/how_to_submit_scores_to_google_sheets.md'>click here to generate a Web App URL</a>";
    echo "                    </div>";
    echo "                </div>";
    echo "            </div>";
    echo "        </div>";
    echo "    </div>";
    echo "</div>";
?>