<?php
    echo "<div class='modal fade' data-bs-backdrop='static' data-keyboard='false' id='modal_settings'>";
    echo "";
    echo "    <div class='modal-dialog' role='document'>";
    echo "";
    echo "        <div class='modal-content'>";
    echo "";
    echo "            <div class='modal-header p-0 justify-content-center' style='position:relative;'>";
    echo "";
    echo "                <h2 class='modal-title h2'>Settings</h2>";
    echo "                <button class='btn astext btn-close-settings' id='button_close_modal_settings' style='position:absolute;right:1em;' type='button'>";
    echo "                    &#x274c;";
    echo "                </button>";
    echo "            </div>";
    echo "";
    echo "            <div class='modal-body' id='modal_settings_body'>";
    echo "";
    echo "                <div class='row mt-1 p-0 justify-content-between margin_auto' id='row_setting_toggle_screen_sleep'>";
    echo "";
    echo "                    <div class='col-5 p-0 align-self-center settings-label'>";
    echo "                        Prevent screen sleep:";
    echo "                    </div>";
    echo "    ";
    echo "                    <div class='col-2 offset-5 p-0 text-end'>";
    echo "                        <label class='switch'>";
    echo "                            <input type='checkbox' id='button_toggle_screen_sleep'>";
    echo "                            <span class='slider round'></span>";
    echo "                        </label>";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row mt-1 p-0 justify-content-center margin_auto' id='row_setting_choose_theme'>";
    echo "";
    echo "                    <div class='col-5 p-0 align-self-center'>";
    echo "                        <label class='settings-label' for='theme'>Theme:</label>";
    echo "                    </div>";
    echo "    ";
    echo "                    <div class='col-7 p-0'>";
    echo "                        <select name='theme' id='theme_options' style='width:100%'>";
    echo "                            <option value='default'>Default</option>";
    echo "                            <option value='bee_eater'>Bee Eater</option>";
    echo "                            <option value='blue_winged_kookaburra'>Blue-winged Kookaburra</option>";
    echo "                            <option value='eastern_rosella'>Eastern Rosella</option>";
    echo "                            <option value='eastern_yellow_robin'>Eastern Yellow Robin</option>";
    echo "                            <option value='galah'>Galah</option>";
    echo "                            <option value='olive_backed_oriole'>Olive-backed Oriole</option>";
    echo "                            <option value='plains_wanderer'>Plains Wanderer</option>";
    echo "                            <option value='princess_parrot'>Princess Parrot</option>";
    echo "                            <option value='rose_crowned_fruit_dove'>Rose-crowned Fruit-dove</option>";
    echo "                            <option value='southern_cassowary'>Southern Cassowary</option>";
    echo "                            <option value='spotted_pardalote'>Spotted Pardalote</option>";
    echo "                            <option value='superb_fairy_wren'>Superb Fairy Wren</option>";
    echo "                        </select>";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row mt-1 p-0 justify-content-center margin_auto' id='row_setting_choose_background'>";
    echo "";
    echo "                    <div class='col-5 p-0 align-self-center'>";
    echo "                        <label class='settings-label' for='background'>Background:</label>";
    echo "                    </div>";
    echo "    ";
    echo "                    <div class='col-7 p-0'>";
    echo "                        <select name='background' id='background_options'  style='width:100%'>";
    echo "                            <option value='random'>Random</option>";
    echo "                            <option value='base_game_forest_habitat'>Base Game (Forest)</option>";
    echo "                            <option value='base_game_grassland_habitat'>Base Game (Grassland)</option>";
    echo "                            <option value='base_game_wetland_habitat'>Base Game (Wetland)</option>";
    echo "                            <option value='european_expansion_forest_habitat'>European Expansion (Forest)</option>";
    echo "                            <option value='european_expansion_grassland_habitat'>European Expansion (Grassland)</option>";
    echo "                            <option value='european_expansion_wetland_habitat'>European Expansion (Wetland)</option>";
    echo "                            <option value='hills_forest_habitat'>Hills (Forest)</option>";
    echo "                            <option value='hills_grassland_habitat'>Hills (Grassland)</option>";
    echo "                            <option value='hills_wetland_habitat'>Hills (Wetland)</option>";
    echo "                            <option value='sakura_forest_habitat'>Sakura (Forest)</option>";
    echo "                            <option value='sakura_grassland_habitat'>Sakura (Grassland)</option>";
    echo "                            <option value='sakura_wetland_habitat'>Sakura (Wetland)</option>";
    echo "                            <option value='summer_solstice_forest_habitat'>Summer Solstice (Forest)</option>";
    echo "                            <option value='summer_solstice_grassland_habitat'>Summer Solstice (Grassland)</option>";
    echo "                            <option value='summer_solstice_wetland_habitat'>Summer Solstice (Wetland)</option>";
    echo "                        </select>";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row mt-1 p-0 justify-content-center margin_auto' id='row_set_web_app_url'>";
    echo "";
    echo "                    <div class='col-5 p-0 align-self-center'>";
    echo "                        <label class='settings-label' for='input_web_app_url'>Web App URL:</label>";
    echo "                    </div>";
    echo "    ";
    echo "                    <div class='col-7 p-0'>";
    echo "                        <input class='w-100' id='input_web_app_url' placeholder='Paste Web App URL here'>";
    echo "                    </div>";
    echo "                </div>";
    echo "";
    echo "                <div class='row mt-1 p-0 justify-content-center margin_auto' id='row_web_app_url_guide'>";
    echo "";
    echo "                    <div class='col-7 offset-5 p-0' style='text-align: center;'>";
    echo "                        <a class='w-100' target='_blank' rel='noopener noreferrer' href='https://github.com/NoahBolohan/wingspan-utilities/blob/main/how_to_submit_scores_to_google_sheets.md'>Generate a Web App URL</a>";
    echo "                    </div>";
    echo "                </div>";
    echo "            </div>";
    echo "        </div>";
    echo "    </div>";
    echo "</div>";
?>